### ISSUE TITLE
Failing to build - TypeError: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by piroinno** [Dealogic/webpack-vsts-extension#94]
Hello,

Please can you upgrade the extension or the underlying webpack cli?

We have encountered the following error:

compilation of the webpack project is started
executing the command: node  "F:\azdoagent\A1\_work\16\s\src\OurApp.Service\node_modules\webpack\bin\webpack.js" --json
F:\azdoagent\A1\_work\16\s\src\OurApp.Service\node_modules\webpack-cli\bin\config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (F:\azdoagent\A1\_work\16\s\src\OurApp.Service\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at F:\azdoagent\A1\_work\16\s\src\OurApp.Service\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (F:\azdoagent\A1\_work\16\s\src\OurApp.Service\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (F:\azdoagent\A1\_work\16\s\src\OurApp.Service\node_modules\webpack\bin\webpack.js:156:2)

**Comment by jkanczler** [comment]
So as I understand it seems the Azure DevOps webpack task is not compatible with webpack version 4.2.0?

**Comment by piroinno** [comment]
Hi @jkanczler , I think the version of the cli just needs to be upgraded / downgraded - see the issue with 4.2.0 here: https://github.com/webpack/webpack/issues/8082

**Comment by jkanczler** [comment]
Thanks, so actually it's a bug in webpack? Okay, but as you can see then in your log

```
F:\azdoagent\A1_work\16\s\src\OurApp.Service\node_modules\webpack\bin\webpack.js:156:2
```

the Azure DevOps task itself is using the webpack-cli what your project is using. If you downgrade the webpack-cli in your project, then the Azure DevOps task will use that.

See the config:

Name | Required | Default Value | Description
-- | -- | -- | --
webpack cli location | true | ./node_modules/webpack/bin/webpack.js | Location of the webpack cli. By default it's the locally installed webpack cli.

**Comment by jkanczler** [comment]
@piroinno, could you solve the issue?
