### ISSUE TITLE
Not working for Webpack 5

### ISSUE THREAD

**Issue by john-jay** [Dealogic/webpack-vsts-extension#95]
My build seems to complete (progress 100%), but then it fails processing the stats. It works on my PC but not on Azure DevOps. I am using webpack 5.32.0,

##[error]TypeError: stats.jsonToString is not a function 
##[debug]Processed: ##vso[task.issue type=error;]TypeError: stats.jsonToString is not a function 
**TypeError: stats.jsonToString is not a function** 
at Object.compile (D:\VSOAGENT1\_work\_tasks\webpack_6752a610-c2f3-11e6-949e-5d3841f133f1\4.2.0\webpackCompiler\WebpackCompiler.js:60:23) 
at D:\VSOAGENT1\_work\_tasks\webpack_6752a610-c2f3-11e6-949e-5d3841f133f1\4.2.0\index.js:43:46 
at next (native) 
at D:\VSOAGENT1\_work\_tasks\webpack_6752a610-c2f3-11e6-949e-5d3841f133f1\4.2.0\index.js:7:71 
at __awaiter (D:\VSOAGENT1\_work\_tasks\webpack_6752a610-c2f3-11e6-949e-5d3841f133f1\4.2.0\index.js:3:12) 
at run (D:\VSOAGENT1\_work\_tasks\webpack_6752a610-c2f3-11e6-949e-5d3841f133f1\4.2.0\index.js:15:12) 
at Object.<anonymous> (D:\VSOAGENT1\_work\_tasks\webpack_6752a610-c2f3-11e6-949e-5d3841f133f1\4.2.0\index.js:53:1)

**Comment by john-jay** [comment]
From Q&A: The jsonToString method no longer exists in Stats.js [for WP5].
By Kwang Suh 10/30/2020

**Comment by DunnJM** [comment]
I'm having the same issue

**Comment by jasonproulxFIRST** [comment]
I am having the same issue. Works locally but get the same error as you on Azure DevOps Pipeline. I am using webpack 5.44.0 and webpack-cli 4.7.2

If you have solved it, I would love to know how!

**Comment by wioletag** [comment]
@DunnJM @john-jay @jasonproulxFIRST were you able to solve this? facing the same issue

**Comment by jasonproulxFIRST** [comment]
> 
> 
> @DunnJM @john-jay @jasonproulxFIRST were you able to solve this? facing the same issue

Yes. The Azure Pipeline Task was using version 4.XX of Webpack which seems to be the newest version available for Azure Tasks. For the local compilation of webpack we use Yarn, so I added a Yarn task with the same command and args as what we do locally and it worked. Not sure if this would apply to your environment, but this is how it ended up working for me. Good luck!

**Comment by DunnJM** [comment]
> @DunnJM @john-jay @jasonproulxFIRST were you able to solve this? facing the same issue

Yep! Essentially did the same as @jasonproulxFIRST, just with a custom npm task.

**Comment by DanielLavrushin** [comment]
@DunnJM @jasonproulxFIRST 
I experience the same issue. What is the custom npm task command you used to solve this issue? Could you  share the details please.

**Comment by DanielLavrushin** [comment]
okay, after spending a little time I found this solution
use a CMD task with follwoing command
`node  ".\node_modules\webpack\bin\webpack.js"  --json  --mode production --output-path "$(Build.BinariesDirectory)\dist"`

**Comment by PilotBob** [comment]
> okay, after spending a little time I found this solution use a CMD task with follwoing command `node ".\node_modules\webpack\bin\webpack.js" --json --mode production --output-path "$(Build.BinariesDirectory)\dist"`

So you solution was not to use this plugin. lol. Ok. Guess there's no chance on this getting fixed either. So, I'll probably make the same choice.
